version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: clinic25
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: clinic25
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
